apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  namespace: app
spec:
  replicas: 2
  selector:
   matchLabels:
    app: app
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
      - name: app
        command: ["nginx"]
        image: yanivro/hello-rapid:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 2